# Documentation: http://docs.travis-ci.com/user/languages/julia
language: julia
notifications:
  email: false
julia:
  - 1.0
  - 1.5
  - nightly
os:
  - linux
  - osx
  - windows
arch:
  - x64
jobs:
  fast_finish: true
  allow_failures:
    - julia: nightly
script:
  - julia --project=. -e 'using Pkg; Pkg.instantiate()'
  - export JULIA_TEST_GROUPS="unit integration"; julia --project=. -e 'using Pkg; Pkg.test("InverseIsing"; coverage=true)'
  - export JULIA_TEST_GROUPS="acceptance"; julia --project=. -e 'using Pkg; Pkg.test("InverseIsing")'
after_success:
  - |
    julia -e '
      using Pkg
      Pkg.add("Coverage")
      using Coverage
      Codecov.submit(process_folder())'
  - |
    julia -e '
      using Pkg
      Pkg.add("Coverage")
      using Coverage
      Coveralls.submit(process_folder())'
